### ISSUE TITLE
Symetrix DSP line

### ISSUE THREAD

**Issue by parisjp** [bitfocus/companion-module-symetrix-dsp#1]
Hi, 

I think it would be nice to add Symetrix to the list of controllable equipment.

They are one of the first broadcast audio DSPs with remote control and have a powerful programing software but the control accesories line is limited and would be great to be able to control the DSPs with Streamdeck.

**Comment by mrsydster** [comment]
Horay! I have pushed the first verion of the Symetrix DSP module. Not final yet, but working pretty stable for me. 

Please create a new issue if needed!

**Comment by josephdadams** [comment]
Saw your note about variable limitations. For what it’s worth, I have made a few modules where I dynamically add new variables. Here is such an example: https://github.com/bitfocus/companion-module-shure-dis-ccu/blob/main/index.js

**Comment by mrsydster** [comment]
@josephdadams Ah that is sick! Will refactor the code to do the same :) Thanks for adding this info!

**Comment by mrsydster** [comment]
@josephdadams other question, maybe not the right spot to ask but I am sure you know: 

Is there a way to include internal feedbacks into the module its presets? I want to include **internal: When button is pushed/latched** into a preset?

**Comment by josephdadams** [comment]
I don’t know. @Julusian would possibly know

**Comment by Julusian** [comment]
No it isn't possible currently.
I have been wondering if we should allow using a select few of the internal actions/feedbacks, but it needs some thought on how to make it safe from changes made to the internal module
