### ISSUE TITLE
Not working on Companion 3.3.1

### ISSUE THREAD

**Issue by chriskooken** [bitfocus/companion-module-symetrix-dsp#11]
Hey @elliotmatson I desperately need this working on companion 3.3.1. I would be willing to pay you to get it working if you have some time to work on it.

**Comment by elliotmatson** [comment]
Hey @chriskooken, it looks like my updates for this module were merged, but never made it into an actual release. I don't have permissions to create a release, but @mrsydster or @josephdadams should!

To hopefully get things working in the meantime, you could download this repository, and then put the parent folder (companion-module-symetrix-dsp) inside your developer modules folder, and it should override the current version. Can you let me know if that works?

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-bundled-modules/actions/runs/9840586874

I tagged a release and sent it to the betas

**Comment by chriskooken** [comment]
@josephdadams awesome. How soon will it be available to download in the beta build? It looks like its still not in there.

**Comment by josephdadams** [comment]
Builds run every 6 hours, so I would say sometime in the next 3-4 hours?

**Comment by chriskooken** [comment]
Hey @elliotmatson, this is mostly working in the beta build...I can't get feedbacks to work though. Is there some hidden way that im not realizing?

**Comment by elliotmatson** [comment]
I'm not sure, I didn't really develop that part of the module, and I've never really used that feature. We are in the middle of a big renovation, so my next few weeks are pretty full, but I might be able to find a bit of time to take a look at it
